apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svc-pod
  template:
    metadata:
      labels:
        app: svc-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.1
        ports:
        - containerPort: 80
