apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
  - name: busybox1
    image: busybox
    command: ['sh', '-c', 'COUNTER=0; while true; do printf "line: $COUNTER\n" >> /output/output.log;sleep 1;$(()); COUNTER=$((COUNTER + 1));done']
    volumeMounts:
    - name: sharedvol
      mountPath: /output
  - name: busybox2
    image: busybox
    args: ['sh', '-c', 'tail -f /output/output.log']
    volumeMounts:
    - name: sharedvol
      mountPath: /output
  volumes:
  - name: sharedvol
    emptyDir: {}