apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.yuval.stable.example # format must be: <plural>.<group>
spec:
  group: yuval.stable.example  #group name to use for REST API: /apis/<group>/<version>
  names:
    kind: WebSite  # The kind to use when creating an instance
    plural: websites # when refering to with kubectl
    singular: website
    shortNames:  # a short name to use - optional
    - site
  scope: Namespaced  # the CRD will be active in a single namespace 
  versions:          #  allows me to have multiple versions of the schema
    - name: v1
      served: true   # so this versions is served by an API
      storage: true  # the API will use THIS version to store the data 
      schema:        # define the data fields available to our objects
        # schema used for validation
        openAPIV3Schema:
          type: object  # for other types:  https://swagger.io/docs/specification/data-models/data-types/
          properties:
            spec:
              type: object
              properties:
                sitename:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
