apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: busybox-a
      image: radial/busyboxplus:curl
      command:
      - sleep
      - "3600"
      volumeMounts:
      - name: pv-storage
        mountPath: /pv-data
