apiVersion: v1
kind: Pod
metadata:
  name: good-exit-pod
spec:
  containers:
    - name: busybox-a
      image: yuvalshaul/python-exit:latest
      lifecycle:
        preStop:
          exec:
            command:
              ["/bin/sh", "-c", "kill -s SIGINT 1"]
      