apiVersion: v1
kind: Pod
metadata:
  name: envvar-pod
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"
    ports:
    - containerPort: 80
    env:
      - name: CONFIGMAP_VAR
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: key2
      - name: SECRET_VAR
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: pass
  
