apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"
    ports:
    - containerPort: 80
    env:
      - name: ENVPASS
        valueFrom:
          configMapKeyRef:
            name: my-config-map
            key: key2
  restartPolicy: OnFailure
  
