apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-deployment
spec:
  replicas: 18
  selector:
    matchLabels:
      app: net-deployment
  template:
    metadata:
      labels:
        app: net-deployment
    spec:
      containers:
      - name: netpod
        image: nicolaka/netshoot:latest
        command:
          - sleep
          - "3600"

