apiVersion: v1
kind: Pod
metadata:
  name: net-pod
spec:
  containers:
  - name: target-container
    image:  nginx
  - name: net-container
    image:  nicolaka/netshoot 
    command:
    - sleep
    - "3600"
