apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment-2
  labels:
    app: busybox2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox-2
  template:
    metadata:
      labels:
        app: busybox-2
    spec:
      containers:
      - name: busybox-2
        image: busybox:latest
        command:
          - sleep
          - "3600"
 