apiVersion: v1
kind: Pod
metadata:
  name: select-pod
spec:
  nodeSelector:
    special: yep  
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"    
