apiVersion: v1
kind: Pod
metadata:
  name: dns-pod
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: net-container
    image:  nicolaka/netshoot 
    command:
    - sleep
    - "3600"
