apiVersion: v1
kind: Pod
metadata:
  name: dns-pod
spec:
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 162.159.25.175    # This one is:  ns2.bluehost.com
    searches:
      - example.com
      - google.com
    options:
      - name: ndots
        value: "3"
  containers:
  - name: net-container
    image:  nicolaka/netshoot 
    command:
    - sleep
    - "3600"
